let articulos = [
  {
    nombre: "Camiseta blanca",
    img: "",
    categoria: "Vestimenta",
    descripcion: "Camiseta de algodón 100% en color blanco, talla M.",
    precio: 20.99,
  },
  {
    nombre: "Pantalones vaqueros",
    img: "",
    categoria: "Vestimenta",
    descripcion: "Pantalones vaqueros clásicos en color azul, talla L.",
    precio: 39.99,
  },
  {
    nombre: "Zapatillas deportivas",
    img: "",
    categoria: "Calzado",
    descripcion: "Zapatillas deportivas en color negro con suela de goma, talla 42.",
    precio: 59.99,
  },
  {
    nombre: "Chaqueta de cuero",
    img: "",
    categoria: "Vestimenta",
    descripcion: "Chaqueta de cuero auténtico en color marrón, talla XL.",
    precio: 149.99,
  },
  {
    nombre: "Vestido estampado",
    img: "",
    categoria: "Vestimenta",
    descripcion: "Vestido corto estampado en tonos azules, talla S.",
    precio: 29.99,
  },
  {
    nombre: "Bolso de mano",
    img: "",
    categoria: "Accesorios",
    descripcion: "Bolso de mano en piel sintética en color rosa, con cierre de cremallera.",
    precio: 24.99,
  },
  {
    nombre: "Pulsera de plata",
    img: "",
    categoria: "Accesorios",
    descripcion: "Pulsera de plata de ley con diseño de cadena.",
    precio: 69.99,
  },
  {
    nombre: "Sombrero de paja",
    img: "Accesorios",
    descripcion: "Sombrero de paja con ala ancha en color natural.",
    precio: 12.99,
  },
  {
    nombre: "Gafas de sol",
    img: "Accesorios",
    descripcion: "Gafas de sol con montura de pasta en color negro y cristales oscuros.",
    precio: 19.99,
  },
  {
    nombre: "Reloj de pulsera",
    img: "Accesorios",
    descripcion: "Reloj de pulsera con correa de cuero marrón y esfera plateada.",
    precio: 89.99,
  },
];
